version: "3.9"

services: 
  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: database_ignite
    restart: always
    environment: 
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=devices
      - MYSQL_ROOT_PASSWORD=test
    ports: 
      - 3306:3306
    volumes: 
      - mysqldata:/data/mysql
  app:
    build: .
    container_name: devices
    restart: always
    ports:
      - 3333:3333
      - 9229:9229
    volumes: 
      - .:/usr/app
    links:
      - database
    depends_on: 
      - database
volumes:
  mysqldata:
    driver: local